BaseUrl= "https://tylerarnold.github.io/hugo_travel/"
LanguageCode= "en-us"
Title= "Tyler and Neesha Travel Blog"
paginate = 5
DisqusShortname = "tylernol"
Copyright = "All rights reserved - 2016"
canonifyurls = true

[params]
  description = "chronicling our travels around the world"
  cover = "images/hooker_valley.jpg"
  author = "Tyler Arnold"
  authorlocation = "Austin, Texas"
  authorwebsite = "http://tylernol.org"
  bio= "my bio"
  # logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "tylerarnold"
  twitterName = "tylernol"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  [[menu.main]]
  name = "Main"
  weight = -120
  identifier = "blog"
  url = "/"
